data class PlayerData(
    val code: Int? = null,
    val `data`: List<Data?>? = null,
    val message: String? = null
) {
    data class Data(
        val aerialSuccessCount: Int? = null,
        val appearanceCount: Int? = null,
        val assistCount: Int? = null,
        val bestCount: Int? = null,
        val clearanceCount: Int? = null,
        val crossPassCount: Int? = null,
        val crossPassSuccessCount: Int? = null,
        val dispossessedCount: Int? = null,
        val dribblesSuccessCount: Int? = null,
        val foulsCount: Int? = null,
        val goals: Int? = null,
        val homeTeam: Boolean? = null,
        val interceptionCount: Int? = null,
        val keyPassCount: Int? = null,
        val leagueId: String? = null,
        val longPassCount: Int? = null,
        val longPassSuccessCount: Int? = null,
        val modifyTime: Int? = null,
        val offsideCount: Int? = null,
        val passCount: Int? = null,
        val passSuccessCount: Int? = null,
        val penaltyGoals: Int? = null,
        val playerId: String? = null,
        val playingTime: Int? = null,
        val rating: String? = null,
        val redCount: Int? = null,
        val season: String? = null,
        val shotBlockedCount: Int? = null,
        val shotCount: Int? = null,
        val shotTargetCount: Int? = null,
        val substituteCount: Int? = null,
        val tackleCount: Int? = null,
        val teamId: String? = null,
        val throughPassCount: Int? = null,
        val throughPassSuccessCount: Int? = null,
        val turnOverCount: Int? = null,
        val yellowCount: Int? = null
    )
}